create user 'MuscleMap'@'localhost' identified by 'MuscleMap';
grant all on musclemap.* to 'MuscleMap'@'localhost';
flush privileges;

create database musclemap;

use musclemap;

create table usuario (
idUsuario int primary key auto_increment,
nome varchar(45),
email varchar(60),
senha varchar(50)
) auto_increment = 100;

select * from usuario;

create table musculos (
idMusculo int primary key auto_increment,
nome varchar(60)
);

select * from musculos;

insert into musculos values
(default, 'Peitoral'),
(default,'Peitoral Superior'),
(default,'Peitoral Medial'),
(default,'Peitoral Inferior'),
(default, 'Ombro'),
(default,'Deltóide Anterior'),
(default,'Deltóide Lateral'),
(default,'Deltóide Posterior'),
(default, 'Bíceps'),
(default,'Bíceps Cabeça Longa'),
(default,'Bíceps Cabeça Curta'),
(default,'Braquial'),
(default,'Abdômen'),
(default, 'Quadríceps'),
(default,'Reto Femoral'),
(default,'Vasto Lateral'),
(default,'Vasto Medial'),
(default,'Adutores'),
(default,'Abdutores'),
(default, 'Costas'),
(default,'Trapézio'),
(default,'Latíssimo do Dorso'),
(default,'Rombóides'),
(default,'Quadrado Lombar'),
(default, 'Tríceps'),
(default,'Tríceps Cabeça Longa'),
(default,'Tríceps Cabeça Lateral'),
(default,'Tríceps Cabeça Medial'),
(default, 'Posterior de Coxa'),
(default,'Bíceps Femoral'),
(default,'Semitendíneoso'),
(default,'Semimembranoso'),
(default, 'Glúteo'),
(default,'Glúteo Máximo'),
(default,'Glúteo Médio'),
(default,'Glúteo Mínimo'),
(default, 'Panturrilha'),
(default,'Gêmeos'),
(default,'Sóleo');

create table treino (
idTreino int primary key auto_increment,
fkUsuario int,
constraint fkTreinoUsuario
foreign key (fkUsuario)
references usuario (idUsuario),
fkMusculo int,
constraint fkTreinoMusculo
foreign key (fkMusculo)
references musculos (idMusculo)
);

create table exercicios (
idExercicio int primary key auto_increment,
fkMusculo int,
constraint fkExerciciosMusculo
foreign key (fkMusculo)
references musculos (idMusculo),
nome varchar(70),
gastoCal float,
descricao varchar(200)
);

insert into exercicios values
(default, 1, 'Supino Reto com Barra', 200, 'Clássico para o peitoral, ativa todas as áreas do músculo dependendo da amplitude e carga.'),
(default, 1, 'Supino Reto com Halteres', 220, 'Oferece maior amplitude de movimento, ativando o peitoral de forma equilibrada.'),
(default, 1, 'Flexão de Braços Tradicional', 250, 'Excelente exercício funcional que recruta toda a musculatura do peitoral, além de deltoides e tríceps.'),
(default, 1, 'Crucifixo com Halteres (Banco Reto)', 170, 'Isola o peitoral em toda sua extensão, proporcionando alongamento e contração eficazes.'),
(default, 1, 'Crossover na Polia', 180, 'Trabalha todo o peitoral ao ajustar o ângulo do cabo, com foco na adução horizontal.'),
(default, 1, 'Peck Deck na Máquina', 150, 'Máquina que isola o peitoral, permitindo trabalhar todas as porções com variações de posicionamento.'),
(default, 1, 'Chest Press na Máquina (Reta)', 140, 'Movimentos convergentes na máquina podem ativar todo o peitoral de forma estável e controlada.'),
(default, 1, 'Flexões com Banda Elástica', 230, 'Adicionar resistência ao movimento básico ativa todo o peitoral e aumenta a intensidade.'),
(default, 1, 'Push-Up com Pegada Ampla', 250, 'Flexões com uma pegada mais aberta aumentam o recrutamento do peitoral em comparação com o tríceps.'),
(default, 2, 'Supino Inclinado com Barra' , 200, 'Trabalha diretamente o peitoral superior, com foco na inclinação do banco (15º-30º).'),
(default, 2, 'Supino Inclinado com Halteres', 220, 'Permite maior amplitude de movimento e maior recrutamento do peitoral superior.'),
(default, 2, 'Crucifixo Inclinado com Halteres', 170, 'Isolamento do peitoral superior, excelente para alongamento e contração.'),
(default, 2, 'Crossover na Polia Baixa (Cabo Inclinado)', 180, 'Simula o movimento de cruzamento dos braços, enfatizando o peitoral superior.'),
(default, 2, 'Press Militar com Halteres ou Barra (em inclinação leve)', 190, 'Embora seja voltado para ombros, a inclinação leve ativa o peitoral superior como músculo auxiliar.'),
(default, 2, 'Peck Deck na Inclinação', 150, 'Máquina que isola o peitoral superior com estabilidade.'),
(default, 2, 'Push-Up com Banda Elástica (Inclinação)', 230, 'Flexão inclinada com resistência adicional da banda elástica.'),
(default, 2, 'Chest Dips com Inclinação para Frente', 300, 'Mergulhos no banco ou paralelas com inclinação para ativar o peitoral superior.'),
(default, 3, 'Supino Reto com Barra', 200, 'O clássico do peitoral, com foco na parte central do músculo.'),
(default, 3, 'Supino Reto com Halteres', 220, 'Oferece maior amplitude de movimento, trabalhando o peitoral medial de forma mais completa.'),
(default, 3, 'Crossover na Polia', 180, 'Trabalha o peitoral medial com ênfase no movimento de adução horizontal dos braços.'),
(default, 3, 'Flexão de Braços Tradicional', 250, 'Um exercício básico, mas eficaz, para ativar o peitoral medial e os estabilizadores.'),
(default, 3, 'Crucifixo Reto com Halteres', 170, 'Isolamento do peitoral, promovendo maior alongamento e contração do peitoral medial.'),
(default, 3, 'Peck Deck na Máquina', 150, 'Isola o peitoral medial, ideal para controle e ênfase na contração.'),
(default, 3, 'Chest Fly com Cabos', 180, 'Variação com cabos que trabalha a adução horizontal, mantendo tensão constante no peitoral medial.'),
(default, 3, 'Flexão de Braços com Pegada Fechada', 270, 'A pegada mais fechada transfere a carga para o peitoral medial e tríceps.'),
(default, 3, 'Squeeze Press com Halteres', 200, 'Com os halteres juntos, o foco é mantido na parte medial do peitoral durante o supino.'),
(default, 3, 'Chest Press na Máquina (Reta ou Convergente)', 140, 'Trabalha o peitoral medial com estabilidade adicional, bom para iniciantes.'),
(default, 4, 'Supino Declinado com Barra', 200, 'Um dos exercícios mais eficazes para ativar o peitoral inferior, devido à posição declinada.'),
(default, 4, 'Supino Declinado com Halteres', 220, 'Oferece maior amplitude e estabilidade, permitindo mais controle do peitoral inferior.'),
(default, 4, 'Crossover na Polia Alta', 180, 'Trabalha o peitoral inferior com ênfase no movimento descendente e adução dos braços'),
(default, 4, 'Dips nas Paralelas', 300, 'Inclinar o tronco para frente durante o movimento aumenta a ativação do peitoral inferior.'),
(default, 4, 'Crucifixo Declinado com Halteres', 170, 'Isola o peitoral inferior, promovendo alongamento e contração máximos.'),
(default, 4, 'Peck Deck (Foco Inferior)', 150, 'Ajustar a máquina para uma posição inferior ativa mais o peitoral inferior.'),
(default, 4, 'Chest Press na Máquina (Declinada ou Convergente)', 140, 'Trabalha o peitoral inferior com estabilidade adicional, ótimo para iniciantes.'),
(default, 4, 'Push-Up com Declinação', 250, 'Flexões feitas com os pés elevados, dando maior ênfase à parte inferior do peitoral.'),
(default, 4, 'Pullover com Halteres (Inclinação Negativa)', 170, 'Quando realizado em banco declinado, recruta mais a porção inferior do peitoral.'),
(default, 4, 'Press com Banda Elástica (Declinada)', 190, 'Simula o movimento de supino declinado, com tensão contínua fornecida pela banda elástica.'),
(default, 4, 'Flexão de Braços Estilo Arquear (Archer Push-Up)', 270, 'Uma flexão avançada que pode colocar mais foco em cada lado do peitoral inferior individualmente.'),
(default, 5, 'Desenvolvimento com Barra (Overhead Press)', 200, 'Clássico exercício composto que trabalha todos os feixes do deltoide, com ênfase no anterior e medial.'),
(default, 5, 'Desenvolvimento com Halteres', 220, 'Maior amplitude de movimento e ativação dos estabilizadores do ombro em comparação à barra.'),
(default, 5, 'Arnold Press', 190, 'Variante do desenvolvimento com rotação dos halteres, ativa todo o ombro e estabilizadores.'), 
(default, 5, 'Push Press', 240, 'Um desenvolvimento com impulso das pernas, ótimo para trabalho explosivo e recrutamento total do ombro.'),
(default, 5, 'Desenvolvimento com Kettlebell (Unilateral ou Duplo)', 210, 'Ativa todos os feixes do deltoide e exige estabilidade do core e dos músculos do ombro.'),
(default, 5, 'Lento com Pegada Neutra (Máquina ou Halteres)', 190, 'Variante do desenvolvimento com menor tensão no trapézio, isolando melhor os deltoides.'),
(default, 5, 'Elevações Diagonais com Halteres', 170, 'Combinação de elevação frontal e lateral, promovendo ativação completa do ombro.'),
(default, 5, 'Snatch com Kettlebell', 250, 'Movimentos explosivos que recrutam todo o ombro, além de músculos do core e estabilizadores.'),
(default, 5, 'Clean and Press com Barra ou Halteres', 300, 'Exercício composto que ativa ombro, trapézio e core em um único movimento dinâmico.'),
(default, 5, 'Pike Push-Up (Flexão Invertida)', 250, 'Variante avançada da flexão que trabalha o ombro como foco principal.'),
(default, 6, 'Desenvolvimento com Barra (Overhead Press)', 200, 'Trabalha intensamente o deltoide anterior, com suporte do deltoide medial e trapézio.'),
(default, 6, 'Desenvolvimento com Halteres', 220, 'Ativa o deltoide anterior de forma equilibrada, com maior amplitude de movimento.'),
(default, 6, 'Arnold Press', 190 ,'Variante do desenvolvimento que inclui rotação, aumentando a ativação do deltoide anterior.'),
(default, 6, 'Levantamento Frontal com Halteres', 170, ' Focado diretamente no deltoide anterior, pode ser realizado unilateral ou bilateralmente.'),
(default, 6, 'Levantamento Frontal com Barra', 180, 'Variante com barra que permite cargas maiores, enfatizando o deltoide anterior.'),
(default, 6, 'Flexão Pike com Ênfase no Ombro', 250, 'Variante de flexão inclinada, coloca a maior parte da carga no deltoide anterior.'),
(default, 6, 'Desenvolvimento Militar na Máquina', 160, 'Alternativa estável para isolar o deltoide anterior sem necessidade de estabilizadores.'),
(default, 6, 'Landmine Press', 180, 'Exercício em barra fixa no chão, ótimo para foco no deltoide anterior e movimentos unilaterais.'),
(default, 7, 'Elevação Lateral com Halteres', 150, 'Exercício clássico que isola o deltoide lateral, promovendo largura e definição.'),
(default, 7, 'Elevação Lateral na Polia', 150, 'A polia mantém a tensão constante durante o movimento, ativando o deltoide lateral ao máximo.'),
(default, 7, 'Elevação Lateral Unilateral (Inclinado)', 160, 'Realizado com o corpo inclinado, aumenta a amplitude de movimento e a ativação do deltoide lateral.'),
(default, 7, 'Arnold Lateral Raise', 170, 'Variante que combina uma rotação externa e elevação lateral para maior recrutamento do deltoide lateral.'),
(default, 7, 'Desenvolvimento com Barra por Trás', 200, 'Foco no deltoide lateral devido à posição dos braços, embora exija cuidado com a mobilidade dos ombros.'),
(default, 7, 'Crossover Lateral Cruzada na Polia', 150, 'Movimentos laterais cruzados com cabos isolam o deltoide lateral com alta eficiência.'),
(default, 7, 'Overhead Lateral Raise', 180, ' Elevações laterais com extensão acima da cabeça, aumentando o trabalho da musculatura lateral e estabilizadora.'),
(default, 7, 'Elevação com Banda Elástica', 140, 'Tensão contínua no deltoide lateral com foco em resistência e controle muscular.'),
(default, 8, 'Face Pulls na Polia', 150, ' Excelente exercício para isolar o deltoide posterior e melhorar a postura.'),
(default, 8, 'Crucifixo Invertido com Halteres', 170, 'Realizado deitado em um banco inclinado ou em pé, trabalha diretamente o deltoide posterior.'),
(default, 8, 'Crucifixo Invertido na Máquina (Reverse Peck Deck)', 150, 'Variante na máquina que permite controle total do movimento e isola o deltoide posterior.'),
(default, 8, 'Pull Apart com Banda Elástica', 130, 'Simples e eficiente, melhora a força do deltoide posterior e do manguito rotador.'),
(default, 8, 'Crucifixo Invertido na Polia Baixa', 170, 'Variante com cabos que mantém a tensão constante no deltoide posterior.'),
(default, 9, 'Rosca Direta com Barra', 150, 'Exercício clássico que trabalha ambas as cabeças do bíceps com foco uniforme.'),
(default, 9, 'Rosca Alternada com Halteres', 150, 'Realizado de forma unilateral, permite maior controle e foco na ativação de cada braço.'),
(default, 9, 'Rosca Zottman', 160, 'Combinação de rosca supinada na subida e pronada na descida, trabalhando todo o bíceps e antebraço.'),
(default, 9, 'Rosca na Polia com Pegada Supinada', 140, 'A polia mantém tensão constante no bíceps durante todo o movimento.'),
(default, 9, 'Rosca em Cabo Cruzado', 160, 'Utiliza as polias cruzadas para isolar o bíceps e aumentar a tensão muscular.'),
(default, 9, 'Barbell Cheat Curl (Rosca com Impulso)', 170, 'Permite uso de cargas mais pesadas, ativando tanto o bíceps quanto os estabilizadores.'),
(default, 10, 'Rosca Inclinada com Halteres', 170, ' Realizada deitado em um banco inclinado, alonga completamente a cabeça longa, promovendo máxima ativação.'),
(default, 10, 'Rosca Direta com Barra (Pegada Fechada)', 150, 'Uma pegada mais estreita na barra concentra o esforço na cabeça longa.'),
(default, 10, 'Rosca Alternada com Supinação', 150, ' A rotação do punho durante a subida maximiza o recrutamento da cabeça longa.'),
(default, 10, 'Rosca na Polia Alta com Corda', 150, 'Movimentos em martelo na polia enfatizam a cabeça longa devido à tensão constante.'),
(default, 10 , 'Curl Drag (Rosca Arrastada)', 140, 'Mantém os cotovelos para trás enquanto a barra é "arrastada" próxima ao corpo, ativando fortemente a cabeça longa.'),
(default, 10, 'Chin-Up (Barra Fixa com Pegada Supinada)', 250, 'Foco no bíceps, especialmente na cabeça longa, enquanto trabalha costas e estabilizadores.'),
(default, 11, 'Rosca Direta com Barra (Pegada Aberta)', 150, 'Usar uma pegada mais larga na barra ativa mais a cabeça curta.'),
(default, 11, 'Rosca Concentrada', 130, 'Isolamento máximo do bíceps, com ênfase na cabeça curta, devido ao suporte do cotovelo na perna.'),
(default, 11, 'Rosca Scott (Banco Scott)', 150, 'Mantém o foco na cabeça curta ao limitar o movimento dos ombros e isolando o bíceps.'),
(default, 11, 'Rosca Spider', 160, 'Executado em um banco inclinado para frente, isola a cabeça curta ao manter os cotovelos à frente do tronco.'),
(default, 12, 'Rosca Martelo', 140, 'Um dos melhores exercícios para o braquial, realizado com pegada neutra.'),
(default, 12, 'Rosca Martelo Cruzada', 140, 'Movimenta o halter na direção do peitoral oposto, aumentando a ativação do braquial.'),
(default, 12, 'Rosca Pronada', 140, 'Com pegada pronada, reduz a ativação do bíceps braquial e aumenta o esforço do braquial.'),
(default, 12, 'Rosca Martelo na Polia (Corda)', 150, 'A tensão constante da polia mantém o braquial ativado ao longo do movimento.'),
(default, 12, 'Rosca Martelo com Pegada na Barra', 140, 'Realizada com uma barra com pegas neutras, ideal para maior recrutamento do braquial.'),
(default, 12, 'Rosca Martelo na Polia Alta', 140, 'Feita em uma polia alta, mantém o braquial sob tensão constante.'),
(default, 12, 'Carregamento Lateral (Farmer’s Walk Lateral)', 200, 'Caminhar segurando pesos com os braços em abdução parcial ativa o deltoide lateral e estabilizadores.'),
(default, 13, 'Prancha', 120, 'Trabalha todo o core isometricamente, promovendo estabilidade e força funcional.'),
(default, 13, 'Rollout com Roda de Abdominal', 160, 'lta ativação do reto abdominal e transverso devido ao movimento de extensão e retorno.'),
(default, 13, 'Bicicleta no Solo', 160, 'Ativa simultaneamente o reto abdominal e os oblíquos.'),
(default, 13, 'Elevação de Pernas na Barra', 180, 'Foco no abdômen inferior, exigindo estabilização do core e força de pegada.'),
(default, 13, 'Mountain Climbers', 300, ' Combina ativação abdominal com trabalho cardiovascular, elevando a frequência cardíaca.'),
(default, 13, 'V-Ups', 160, 'Trabalha intensamente toda a extensão do reto abdominal.'),
(default, 13, 'Torção Russa (Com Peso)', 140, 'Foco nos oblíquos e força rotacional do tronco.'),
(default, 14, 'Agachamento Livre', 280, 'Foco no quadríceps por completo, com ênfase maior no vasto medial ao atingir a profundidade.'),
(default, 14, 'Leg Press', 240, 'Quadríceps completo, dependendo da posição dos pés na plataforma: Pés baixos na plataforma: Maior ênfase no quadríceps. Pés mais altos: Inclui mais posterior de coxa e glúteos.'),
(default, 14, 'Passada com Barra ou Halteres', 300, 'Quadríceps completo e estabilização, com destaque para o vasto medial ao descer.'),
(default, 14, 'Agachamento Búlgaro', 280, 'Foco em quadríceps completo, com grande ativação unilateral e estabilidade. Mantendo o tronco ereto para maior foco nos quadríceps.'),
(default, 14, 'Cadeira Extensora', 140, 'Quadríceps completo, isolando o movimento do joelho.'),
(default, 15, 'Cadeira Extensora com Inclinação do Tronco', 140, 'Maior ativação no reto femoral devido ao ângulo do quadril.'),
(default, 15, 'Skater Squat', 250, 'Trabalha o reto femoral com maior intensidade por ser um movimento unilateral que exige equilíbrio.'),
(default, 15, 'Sprint em Subida', 400, 'Trabalha o reto femoral devido à explosão de força em flexão de quadril.'),
(default, 16, 'Agachamento Sumô', 280, 'Maior ênfase no vasto lateral devido à posição ampla das pernas.'),
(default, 16, 'Leg Press com Pés Juntos', 240, 'A posição próxima dos pés intensifica o trabalho no vasto lateral.'),
(default, 16, 'Hack Squat', 240, 'Vasto lateral e reto femoral trabalhados. A máquina guia o movimento, facilitando a ativação específica.'),
(default, 16, 'Cadeira Extensora com Ponta dos Pés para Fora', 140, 'Maior ativação do vasto medial ao alterar o ângulo do pé.'),
(default, 16, 'Sissy Squat', 220, 'Isola o vasto medial, estendendo e alongando profundamente o quadríceps.'),
(default, 16, 'Step-Up com Pegada Próxima', 260, 'Ao manter os pés juntos no degrau, o vasto medial é mais exigido.'),
(default, 17, 'Cadeira Adutora', 140, 'Trabalha diretamente os músculos adutores em isolamento.'),
(default, 17, 'Sumo Deadlift (Levantamento Terra Sumô)', 300, 'Ativa adutores e glúteos devido à posição ampla dos pés.'),
(default, 17, 'Agachamento Sumô', 280, 'Grande ênfase nos adutores, além de quadríceps e glúteos.'),
(default, 17, 'Passada Lateral', 240, 'Trabalha intensamente os adutores de forma unilateral.'),
(default, 17, 'Squeeze com Bola (Isométrico)', 100, 'Isolamento dos adutores por contração isométrica.'),
(default, 18, 'Cadeira Abdutora', 140, 'Trabalha diretamente os músculos abdutores em isolamento.'),
(default, 18, 'Ponte com Faixa de Resistência', 160, 'Trabalha glúteos e abdutores, especialmente ao afastar os joelhos contra a resistência.'),
(default, 18, 'Caminhada com Faixa de Resistência', 200, 'Ativa intensamente os abdutores, além de glúteos e estabilizadores do quadril.'),
(default, 18, 'Agachamento com Abertura Lateral', 240, 'Combina abdutores e glúteos, aumentando a amplitude de movimento.'),
(default, 19, 'Levantamento Terra', 350, 'Exercício composto que ativa costas, glúteos, quadríceps e core; essencial para força geral.'),
(default, 19, 'Barra Fixa (Pegada Pronada)', 300, 'Trabalha costas completas, com foco no latíssimo e trapézio; também ativa bíceps e core.'),
(default, 19, 'Remada Curvada com Barra', 280, 'Fortalece a região superior e média das costas; foca nos rombóides, trapézio e latíssimo.'),
(default, 19, 'Pulley Frontal (Pegada Aberta)', 220, 'Isola o latíssimo do dorso, trabalhando costas superiores e estabilizadores.'),
(default, 19, 'Remada Unilateral com Halteres', 240, 'Trabalha unilateralmente o latíssimo, rombóides e trapézio inferior.'),
(default, 20, 'Encolhimento de Ombros com Halteres', 160, 'Isola o trapézio superior; ideal para ganho de força e estabilidade cervical.'),
(default, 20, ' Face Pull (Cabo ou Elástico)', 140, 'Fortalece o trapézio superior e médio, além dos deltoides posteriores.'),
(default, 20, 'Levantamento Terra com Pegada Snatch', 350, ' Foco extra no trapézio superior devido à amplitude maior da pegada.'),
(default, 20 ,'Power Shrug', 280 , 'Combina movimento de encolhimento com explosão para trapézio e força explosiva geral.'),
(default, 21, 'Barra Fixa (Pegada Supinada)', 300, ' Trabalha intensamente o latíssimo do dorso, além de bíceps e trapézio inferior.'),
(default, 21, 'Remada Cavalo (T-Bar Row)', 260, 'Fortalece latíssimo, trapézio inferior e rombóides com pegada neutra ou aberta.'),
(default, 21, 'Pull Over com Halteres', 180, 'Alongamento e fortalecimento do latíssimo, especialmente em movimentos de puxada.'),
(default, 21, 'Remada no Pulley com Pegada Aberta', 220, 'Trabalha a largura das costas, com foco no latíssimo do dorso e rombóides.'),
(default, 22, ' Remada Invertida', 200, 'Utiliza o peso do corpo para ativar rombóides, trapézio e estabilizadores.'),
(default, 22, 'Face Pull', 140, 'Trabalha rombóides e trapézio médio com movimento de retração escapular.'),
(default, 22, 'Crucifixo Invertido com Halteres', 160, 'Isola rombóides e deltoides posteriores em um movimento de abertura.'),
(default, 22, 'Remada Alta (Com Cabo ou Halteres)', 200, 'Foco na parte média das costas, ativando rombóides e trapézio superior.'),
(default, 23, 'Extensão Lombar no Banco', 160, 'Trabalha diretamente o quadrado lombar, além dos eretores espinhais.'),
(default, 23, 'Side Plank (Prancha Lateral)', 120, ' Isométrico que ativa o quadrado lombar e músculos estabilizadores.'),
(default, 23, 'Bom Dia', 240, 'Fortalece o quadrado lombar e glúteos com movimento controlado de flexão de quadril.'),
(default, 23, 'Levantamento Terra Romeno', 280, 'Combina quadrado lombar, glúteos e posteriores de coxa em um único movimento.'),
(default, 24, 'Tríceps Pulley (Pegada Pronada)', 180, 'Trabalha todas as cabeças do tríceps com foco na lateral e medial; ótimo para isolar o músculo'),
(default, 24, 'Paralelas (Dips)', 280, 'Movimento composto que ativa o tríceps por completo, com ênfase na longa.'),
(default, 24, 'Supino Fechado', 260, 'Ativa o tríceps inteiro e também o peitoral interno; ideal para força e hipertrofia.'),
(default, 24, 'Extensão de Tríceps com Halteres (Sobre a Cabeça)', 200, 'Foco em alongar e trabalhar todas as cabeças do tríceps, com ênfase na longa.'),
(default, 24, 'Kickback de Tríceps', 160, 'Movimento unilateral que trabalha todas as cabeças do tríceps com grande isolamento.'),
(default, 25, 'Extensão com Halteres (Unilateral ou Bilateral, Sobre a Cabeça)', 200, 'Estira e trabalha intensamente a cabeça longa em sua amplitude máxima.'),
(default, 25, 'Tríceps Testa (Skull Crusher, Barra ou Halteres)', 180, 'Ativa principalmente a cabeça longa, com envolvimento das demais.'),
(default, 25, 'Extensão de Tríceps na Polia Alta (Corda, Pegada Neutra)', 180, 'Foco na cabeça longa, permitindo alongamento e contração controlados.'),
(default, 26, 'Tríceps Pulley (Pegada Invertida)', 180, 'Destaca a cabeça lateral com movimento controlado e pegada diferenciada.'),
(default, 26, 'Kickback com Halteres', 160, 'Trabalha a lateral com isometria no ponto de contração máxima.'),
(default, 26, 'Extensão de Tríceps com Corda (Polia Alta)', 180, 'Permite maior separação das cordas na fase final para enfatizar a cabeça lateral.'),
(default, 26, 'Bench Dips', 240, 'Enfatiza a cabeça lateral enquanto também ativa as demais.'),
(default, 27, 'Tríceps Pulley com Pegada Fechada', 180, 'Isola a cabeça medial, especialmente na fase de extensão completa.'),
(default, 27, 'Tríceps Corda com Rotação Final', 280, 'Movimento final de rotação enfatiza a cabeça medial durante o exercício.'),
(default, 27, 'Close-Grip Push-Ups (Flexão com Pegada Fechada)', 260, ' Grande ênfase na cabeça medial enquanto trabalha o tríceps como um todo.'),
(default, 27, 'Extensão de Tríceps Isométrica (Corda ou Halter)', 150, 'Contração estática que ativa fortemente a cabeça medial para estabilidade.'),
(default, 28, 'Levantamento Terra Romeno', 280, 'Trabalha isquiotibiais e glúteos com foco no alongamento e fortalecimento do posterior.'),
(default, 28, 'Stiff com Halteres', 260, 'Variação que alonga profundamente o posterior de coxa, com grande ativação do bíceps femoral.'),
(default, 28, 'Bom dia', 240, 'Isola o posterior e ativa também glúteos e lombar; ideal para mobilidade e força.'),
(default, 28, 'Cadeira Flexora (Flexão de Joelhos)', 160, 'Trabalha diretamente o posterior de coxa; ótimo para isolar os isquiotibiais.'),
(default, 28, 'Glute Ham Raise (Elevação com Apoio)', 180, 'Exercício avançado que foca em posterior, glúteos e eretores da coluna.'),
(default, 28, 'Kettlebell Swing', 300, 'Movimento explosivo que ativa posterior, glúteos e core; ideal para potência.'),
(default, 29, 'Levantamento Terra Convencional', 350, 'Exercício composto que fortalece posterior, glúteos e lombar.'),
(default, 29, 'Stiff com Barra', 260, 'Variante que alonga profundamente o bíceps femoral durante o movimento.'),
(default, 29, 'Hip Thrust com Foco no Posterior', 200, 'Elevação do quadril com ênfase nos isquiotibiais e glúteos.'),
(default, 29, 'Swing com Dumbbell', 300, 'Alternativa ao kettlebell swing, ativando o bíceps femoral e glúteos.'),
(default, 30, 'Nordic Curl', 180, 'Flexão controlada que ativa fortemente o semitendíneo devido ao movimento excêntrico.'),
(default, 30, 'Bola Suíça (Flexão com Estabilidade)', 140, 'A instabilidade aumenta o recrutamento do semitendíneo, exigindo maior estabilização.'),
(default, 30, 'Flexão Isométrica (Máquina ou Bola)', 130, 'A contração estática em posição de flexão destaca o semitendíneo na estabilização.'),
(default, 31, 'Cadeira Flexora Unilateral', 160, 'Flexão concentrada do joelho, com maior isolamento e ativação do semimembranoso.'),
(default, 31, 'Glute Ham Raise (com Foco no Inferior)', 180, 'Estende o quadril e flexiona o joelho, acionando o semimembranoso em estabilização profunda.'),
(default, 32, 'Agachamento Livre', 350, 'Movimento composto que ativa todos os músculos do glúteo, além de quadríceps e posterior.'),
(default, 32, 'Levantamento Terra', 300, 'Trabalha glúteos e posteriores em sinergia, com grande ênfase no máximo.'),
(default, 32, 'Afundo (Lunges)', 280, 'Trabalha glúteos de forma completa, especialmente em posições profundas.'),
(default, 32, 'Hip Thrust', 280, 'Foco principal no glúteo máximo, mas ativa o médio e mínimo para estabilização.'),
(default, 32, 'Step-Up com Carga', 260, 'Ativa o glúteo completo ao subir, com maior ênfase no máximo e médio.'),
(default, 33, 'Hip Thrust com Carga Pesada', 280, 'Trabalha o glúteo máximo em amplitude máxima, com foco no topo do movimento.'),
(default, 33, 'Ponte Glútea (Glute Bridge)', 180, 'Variante de solo que isola o glúteo máximo, ideal para iniciantes ou alta repetição.'),
(default, 33, 'Levantamento Terra Romeno', 280, 'Enfatiza o alongamento e contração do glúteo máximo junto ao posterior.'),
(default, 33, 'Agachamento Profundo', 350, 'A maior amplitude ativa mais o glúteo máximo durante a subida.'),
(default, 34, 'Abdução na Cadeira', 160, 'Movimento isolado que enfatiza o glúteo médio, ótimo para hipertrofia.'),
(default, 34, 'Caminhada Lateral com Mini Band', 140, 'Trabalha o glúteo médio e mínimo com resistência constante.'),
(default, 34, 'Side-Lying Hip Abduction (Elevação Lateral de Perna)', 130, 'Elevação lateral isolada que foca no médio e mínimo para abdução.'),
(default, 34, 'Step-Up Lateral', 260, 'Variante do step-up que ativa fortemente o glúteo médio na estabilização.'),
(default, 35, 'Caminhada Lateral com Mini Band', 140, 'Resistência ativa o glúteo mínimo, ótimo para fortalecimento.'),
(default, 35, 'Side-Lying Clam Shell', 120, 'Movimentos curtos para ativar o glúteo mínimo na abdução e rotação.'),
(default, 35, 'Abdução em Polia Baixa', 160, 'Resistência contínua que ativa o glúteo mínimo ao movimentar a perna lateralmente.'),
(default, 35, 'Prancha Lateral com Elevação de Perna', 180, 'Combina força de core e ativação do glúteo mínimo na abdução.'),
(default, 36, 'Elevação de Panturrilha em Pé (com Peso)', 200, 'Trabalha a panturrilha completa; gêmeos predominam pela posição estendida.'),
(default, 36, 'Corrida ou Caminhada em Inclinação', 400, 'Ativa toda a panturrilha durante a impulsão; ótimo para resistência.'),
(default, 36, 'Salto com Peso (Plyométrico)', 350, 'Movimentos explosivos ativam os gêmeos e sóleo para força e potência.'),
(default, 36, 'Sled Push (Empurrar Trenó)', 400, 'Grande ativação da panturrilha como um todo, com foco em força isométrica e explosiva.'),
(default, 37, 'Elevação de Panturrilha em Pé na Barra Smith', 200, 'Isola os gêmeos com carga controlada; aumenta a força e hipertrofia.'),
(default, 37, 'Elevação de Panturrilha Unilateral (com Haltere)', 180, 'Concentração em cada perna, permitindo maior ênfase nos gêmeos.'),
(default, 37, 'Saltos Verticais com Peso', 350, 'Movimento explosivo para potência nos gêmeos, especialmente o lateral.'),
(default, 37, 'Corrida em Sprint', 500, 'Movimentos rápidos ativam intensamente os gêmeos para estabilidade e força.'),
(default, 38, 'Elevação de Panturrilha Sentado (com Peso)', 180, 'Trabalha profundamente o sóleo com movimentos concentrados e controlados.'),
(default, 38, 'Ponte com Elevação de Calcanhares', 150, 'Combina trabalho do sóleo com estabilização do quadril.'),
(default, 38, 'Step-Up Isométrico na Ponta dos Pés', 160, 'Mantém o sóleo ativo em posição de flexão plantar sustentada.'),
(default, 38, 'Pliometria em Degraus', 300, 'Saltos controlados em degraus enfatizam o sóleo devido à flexão do joelho.');

select * from exercicios;

create table exerciciosTreino (
fkExercicio int,
fkTreino int,
primary key (fkExercicio, fkTreino),
constraint fkExTreinoEx
foreign key (fkExercicio)
references exercicios (idExercicio),
constraint fkExTreinoTreino
foreign key (fkTreino)
references treino (idTreino)
);

select * from treino;

select * from exerciciosTreino;

select m.nome as 'Músculo',
sum(e.gastoCal) as 'Total Calorias'
from exerciciosTreino as et 
join exercicios as e on e.idExercicio = et.fkExercicio 
join treino t on t.idTreino = et.fkTreino 
join musculos m on m.idMusculo = t.fkMusculo
group by et.fkTreino;